version: "3"

services:
  node-ts:
    build:
      context: ./node-ts
      dockerfile: Dockerfile
      args:
        PORT: 8050
        HOST: 0.0.0.0
    ports:
      - "5555:7070"
    environment:
      PORT: 7070

